POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3Rpa8OkeXR0w6Rqw6QyIiwiaWQiOiI2NTI0MWUxN2M3MDliYzA4MzIxYmQ0MTUiLCJpYXQiOjE2OTY4NjU4OTV9.O-K2rolU0FmE9Is9TbMxagVka5wD4Wfr5upZOZj61Nk

{
    "title": "jotain2",
    "author": "kirjoittaja2",
    "url": "jotainjotain.com",
    "likes": 42,
    "userId": "65241e17c709bc08321bd415"
}